class TestConstants {
    testGroupListArray = [
        {
            id: "bsd12389",
            name: "Omer's Party",
            members: [
                "David",
                "Omer"
            ]
        },
        {
            id: "kbjhafweoyfewo",
            name: "Household",
            members: [
                "David",
                "Omer",
                "Eran",
                "Leor"
            ],
            groupIcon: "🪴"
        },
        {
            id: "ginouc2eon7gn2noi",
            name: "Cyprus Vacation",
            members: [
                "David",
                "Eran",
                "Luly",
                "Nitzan",
                "Ayelet"
            ]
        }
    ]

    testSingleGroup = {
        id: "householdTest",
        name: "Household",
        members: [
            "David",
            "Omer",
            "Eran",
            "Leor"
        ],
        groupIcon: "🪴",
        transactions: [
            { lender: "David", borrower: "Omer", amount: 500, transactionType: false },
            { lender: "Eran", borrower: "Omer", amount: 500, transactionType: true },
            { lender: "Leor", borrower: "Omer", amount: 500, transactionType: false },
            { lender: "Omer", borrower: "David", amount: 200, transactionType: true },
            { lender: "David", borrower: "Leor", amount: 300, transactionType: false },
            { lender: "Eran", borrower: "Leor", amount: 150, transactionType: true },
            { lender: "Omer", borrower: "Eran", amount: 250, transactionType: false },
            { lender: "Leor", borrower: "David", amount: 100, transactionType: true },
            { lender: "David", borrower: "Eran", amount: 600, transactionType: false },
            { lender: "Omer", borrower: "Leor", amount: 450, transactionType: true },
            { lender: "Eran", borrower: "David", amount: 350, transactionType: false },
            { lender: "Leor", borrower: "Eran", amount: 400, transactionType: true },
            { lender: "Omer", borrower: "David", amount: 100, transactionType: false },
            { lender: "David", borrower: "Omer", amount: 550, transactionType: true },
            { lender: "Leor", borrower: "Omer", amount: 250, transactionType: false },
            { lender: "Omer", borrower: "David", amount: 200, transactionType: true },
            { lender: "David", borrower: "Leor", amount: 300, transactionType: false },
            { lender: "Eran", borrower: "Leor", amount: 150, transactionType: true },
            { lender: "Omer", borrower: "Eran", amount: 250, transactionType: false },
            { lender: "Leor", borrower: "David", amount: 100, transactionType: true },
            { lender: "David", borrower: "Eran", amount: 600, transactionType: false },
            { lender: "Omer", borrower: "Leor", amount: 450, transactionType: true },
            { lender: "Eran", borrower: "David", amount: 350, transactionType: false },
            { lender: "Leor", borrower: "Eran", amount: 400, transactionType: true },
            { lender: "Omer", borrower: "David", amount: 100, transactionType: false },
            { lender: "David", borrower: "Omer", amount: 550, transactionType: true },
            { lender: "Leor", borrower: "Omer", amount: 250, transactionType: false },
            { lender: "Omer", borrower: "David", amount: 200, transactionType: true },
            { lender: "David", borrower: "Leor", amount: 300, transactionType: false },
            { lender: "Eran", borrower: "Leor", amount: 150, transactionType: true },
            { lender: "Omer", borrower: "Eran", amount: 250, transactionType: false },
            { lender: "Leor", borrower: "David", amount: 100, transactionType: true },
            { lender: "David", borrower: "Eran", amount: 600, transactionType: false },
            { lender: "Omer", borrower: "Leor", amount: 450, transactionType: true },
            { lender: "Eran", borrower: "David", amount: 350, transactionType: false },
            { lender: "Leor", borrower: "Eran", amount: 400, transactionType: true },
            { lender: "Omer", borrower: "David", amount: 100, transactionType: false },
            { lender: "David", borrower: "Omer", amount: 550, transactionType: true },
            { lender: "Leor", borrower: "Omer", amount: 250, transactionType: false },
            { lender: "Omer", borrower: "David", amount: 200, transactionType: true },
            { lender: "David", borrower: "Leor", amount: 300, transactionType: false },
            { lender: "Eran", borrower: "Leor", amount: 150, transactionType: true },
            { lender: "Omer", borrower: "Eran", amount: 250, transactionType: false },
            { lender: "Leor", borrower: "David", amount: 100, transactionType: true },
            { lender: "David", borrower: "Eran", amount: 600, transactionType: false },
            { lender: "Omer", borrower: "Leor", amount: 450, transactionType: true },
            { lender: "Eran", borrower: "David", amount: 350, transactionType: false },
            { lender: "Leor", borrower: "Eran", amount: 400, transactionType: true },
            { lender: "Omer", borrower: "David", amount: 100, transactionType: false },
            { lender: "David", borrower: "Omer", amount: 550, transactionType: true },
            { lender: "Leor", borrower: "Omer", amount: 250, transactionType: false },
            { lender: "Omer", borrower: "David", amount: 200, transactionType: true },
            { lender: "David", borrower: "Leor", amount: 300, transactionType: false },
            { lender: "Eran", borrower: "Leor", amount: 150, transactionType: true },
            { lender: "Omer", borrower: "Eran", amount: 250, transactionType: false },
            { lender: "Leor", borrower: "David", amount: 100, transactionType: true },
            { lender: "David", borrower: "Eran", amount: 600, transactionType: false },
            { lender: "Omer", borrower: "Leor", amount: 450, transactionType: true },
            { lender: "Eran", borrower: "David", amount: 350, transactionType: false },
            { lender: "Leor", borrower: "Eran", amount: 400, transactionType: true },
            { lender: "Omer", borrower: "David", amount: 100, transactionType: false },
            { lender: "David", borrower: "Omer", amount: 550, transactionType: true },
            { lender: "Leor", borrower: "Omer", amount: 250, transactionType: false },
            { lender: "Omer", borrower: "David", amount: 200, transactionType: true },
            { lender: "David", borrower: "Leor", amount: 300, transactionType: false },
            { lender: "Eran", borrower: "Leor", amount: 150, transactionType: true },
            { lender: "Omer", borrower: "Eran", amount: 250, transactionType: false },
            { lender: "Leor", borrower: "David", amount: 100, transactionType: true },
            { lender: "David", borrower: "Eran", amount: 600, transactionType: false },
            { lender: "Omer", borrower: "Leor", amount: 450, transactionType: true },
            { lender: "Eran", borrower: "David", amount: 350, transactionType: false },
            { lender: "Leor", borrower: "Eran", amount: 400, transactionType: true },
            { lender: "Omer", borrower: "David", amount: 100, transactionType: false },
            { lender: "David", borrower: "Omer", amount: 550, transactionType: true },
            { lender: "Leor", borrower: "Omer", amount: 250, transactionType: false },
            { lender: "Omer", borrower: "David", amount: 200, transactionType: true },
            { lender: "David", borrower: "Leor", amount: 300, transactionType: false },
            { lender: "Eran", borrower: "Leor", amount: 150, transactionType: true },
            { lender: "Omer", borrower: "Eran", amount: 250, transactionType: false },
            { lender: "Leor", borrower: "David", amount: 100, transactionType: true },
            { lender: "David", borrower: "Eran", amount: 600, transactionType: false },
            { lender: "Omer", borrower: "Leor", amount: 450, transactionType: true },
            { lender: "Eran", borrower: "David", amount: 350, transactionType: false },
            { lender: "Leor", borrower: "Eran", amount: 400, transactionType: true },
            { lender: "Omer", borrower: "David", amount: 100, transactionType: false },
            { lender: "David", borrower: "Omer", amount: 550, transactionType: true },
            { lender: "Leor", borrower: "Omer", amount: 250, transactionType: false },
            { lender: "Omer", borrower: "David", amount: 200, transactionType: true },
            { lender: "David", borrower: "Leor", amount: 300, transactionType: false },
            { lender: "Eran", borrower: "Leor", amount: 150, transactionType: true },
            { lender: "Omer", borrower: "Eran", amount: 250, transactionType: false },
            { lender: "Leor", borrower: "David", amount: 100, transactionType: true },
            { lender: "David", borrower: "Eran", amount: 600, transactionType: false },
            { lender: "Omer", borrower: "Leor", amount: 450, transactionType: true },
            { lender: "Eran", borrower: "David", amount: 350, transactionType: false },
            { lender: "Leor", borrower: "Eran", amount: 400, transactionType: true },
            { lender: "Omer", borrower: "David", amount: 100, transactionType: false },
            { lender: "David", borrower: "Omer", amount: 550, transactionType: true },
            { lender: "Leor", borrower: "Omer", amount: 250, transactionType: false },
        ],
    }
}

const testConstants = new TestConstants()
export default testConstants